### ISSUE TITLE
Post-php-8.1 upgrade fixes

### ISSUE THREAD

**Issue by mariacha** [wri/wri_sites#150]
**Describe the bug**
After the 8.1 php updates in release 9.1.13 and 9.1.14, we are seeing  some warnings that should get fixed:

- [x] on search results pages like https://www.wri.org/search?keys=somalia
```
Deprecated function: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in Drupal\search_api\Plugin\search_api\processor\Highlight->createExcerpt() (line 474 of /code/web/modules/contrib/search_api/src/Plugin/search_api/processor/Highlight.php)
#0 /code/web/core/includes/bootstrap.inc(347): _drupal_error_handler_real(8192, 'str_replace(): ...', '/code/web/modul...', 474)
#1 [internal function]: _drupal_error_handler(8192, 'str_replace(): ...', '/code/web/modul...', 474)
#2 /code/web/modules/contrib/search_api/src/Plugin/search_api/processor/Highlight.php(474): str_replace(Array, Array, NULL)
#3 /code/web/modules/contrib/search_api/src/Plugin/search_api/processor/Highlight.php(312): Drupal\search_api\Plugin\search_api\processor\Highlight->createExcerpt(NULL, Array)
#4 /code/web/modules/contrib/search_api/src/Plugin/search_api/processor/Highlight.php(266): Drupal\search_api\Plugin\search_api\processor\Highlight->addExcerpts(Array, Array, Array)
#5 /code/web/modules/contrib/search_api/src/Entity/Index.php(675): Drupal\search_api\Plugin\search_api\processor\Highlight->postprocessSearchResults(Object(Drupal\search_api\Query\ResultSet))
```

See if there's a patch to the `search_api` module.

**Comment by mariacha** [comment]
Confirmed on: 
- [ ] Brasil: https://develop-wri-brasil.pantheonsite.io/search?keys=mundo
- [ ] China:
- [ ] Indonesia:

**Comment by mariacha** [comment]
The patch doesn't seem to fix the issue on Flagship, so I'm putting this back in the backlog.

**Comment by mariacha** [comment]
Confirming there's no error in the logs when searching https://develop-wriflagship.pantheonsite.io/search?keys=somalia so moving to Ready to Deploy
